# Example PlatformIO Project Configuration Override
# ------------------------------------------------------------------------------
# Copy to platformio_override.ini to activate overrides
# ------------------------------------------------------------------------------
# Please visit documentation: https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = c3
extra_configs =
  platformio_override.ini

[env:c3]
framework = arduino
; upload_port = /dev/cu.SLAB_USBtoUART
; monitor_port = /dev/cu.SLAB_USBtoUART
monitor_speed = 115200
platform = espressif32
board = esp32-c3-devkitc-02
monitor_filters = esp32_exception_decoder
build_flags = -Ofast -D USE_ESP_NOW -D USE_I2S_MIC_INPUT
upload_protocol = esp-builtin
platform_packages = tool-openocd-esp32@2.1200.20230419
;board_flags = 
;  -DARDUINO_USB_CDC_ON_BOOT=1
;  -DARDUINO_USB_MODE=1
