; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lolin32
extra_configs =
  platformio_override.ini

[env]
framework = arduino
; upload_port = /dev/cu.SLAB_USBtoUART
; monitor_port = /dev/cu.SLAB_USBtoUART
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags = -Ofast

[env:tinypico]
board = tinypico
platform = espressif32@3.4.0
lib_deps = tinypico/TinyPICO Helper Library@^1.4.0
build_flags = -Ofast -D USE_I2S_MIC_INPUT -D USE_ESP_NOW

[env:lolin32]
board = lolin32
platform = espressif32@3.4.0
build_flags = -Ofast -D USE_I2S_MIC_INPUT -D USE_ESP_NOW
lib_ignore = indicator_led_pico

;[platformio]
;default_envs = c3
;extra_configs =
;  platformio_override.ini

;[env:c3]
;framework = arduino
; upload_port = /dev/cu.SLAB_USBtoUART
; monitor_port = /dev/cu.SLAB_USBtoUART
;monitor_speed = 115200
;platform = espressif32
;board = esp32-c3-devkitc-02
;monitor_filters = esp32_exception_decoder
;build_flags = -Ofast -D USE_ESP_NOW -D USE_I2S_MIC_INPUT
;upload_protocol = esp-builtin
;platform_packages = tool-openocd-esp32@2.1200.20230419
;board_flags = 
;  -DARDUINO_USB_CDC_ON_BOOT=1
;  -DARDUINO_USB_MODE=1
